routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/lava');
});

Route::get('/blog', [MainController::class, 'index'])->name('home');

Route::get('post/{slug}', [MainController::class, 'post'])->name('post');

Route::get('contact', function () {
    return view('contact');
});
Route::get('about', function () {
    return view('about');
});

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'loginPost'])->name('login.post');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerPost'])->name('register.post');

Route::middleware(['IsAdmin', 'IsApproved'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('posts/{id}', [PostController::class, 'destroy'])->whereNumber('id')->name('posts.destroy');
    Route::get('/', [DashboardController::class, 'index'])->name('index');
    Route::resource('posts', PostController::class);

    Route::get('users', [UserController::class, 'index'])->name('users');
    Route::get('users/{id}/edit', [UserController::class, 'edit'])->name('user.edit');
    Route::put('users/{id}/update', [UserController::class, 'update'])->name('user.update');
    Route::get('users/{id}', [UserController::class, 'destroy'])->name('user.destroy');
});

resources/views/admin/index.blade.php
@extends('admin.layouts.master')
@include('admin.layouts.sidebar')
@section('title', 'Laravel Blogs')
@section('content')
    <div id="content">
        @include('admin.layouts.topbar')
        @if (Session::has('success'))
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i> {{ Session::get('success') }}
            </div>
        @endif
@include('errors.200')
    </div>
@endsection

resources/views/admin/login.blade.php
@extends('admin.layouts.header')

<body class="bg-gradient-danger">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="my-5 border-0 shadow-lg card o-hidden">
                    <div class="p-3 p-md-5 card-body">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block p-3 p-md-5 text-center border-danger border-right"><img class="img-fluid" src="https://mesinkasironline.web.app/img/createwebsitelaravel.png"/></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
									<img src="/img/lavas.svg"/>
                                        <h1 class="mb-4 text-gray-900 h4">Hello Artisan !!</h1>
                                        @if (Session::has('success'))
                                            <div class="alert alert-success">
                                                <i class="fas fa-check-circle"></i> {{ Session::get('success') }}
                                            </div>
                                        @endif
                                    </div>
                                    <form class="user" method="post" action="{{ route('login.post') }}">
                                        @csrf
                                        <div class="form-group">
                                            <input type="email" name="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Email Address">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password"
                                                class="form-control form-control-user" id="exampleInputPassword"
                                                placeholder="Input Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember me</label>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-danger btn-user btn-block">
                                            Get Started →
                                        </button>
                                      
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a href="https://axcora.com/getaxcoracms" class="text-danger">axcora technology</a>
                                    </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</body>

resources/views/admin/post-create.blade.php
@extends('admin.layouts.master')
@include('admin.layouts.sidebar')
@section('title', 'New Post')
@section('title')
@section('subtitle')
@section('content')
    <!-- Main Content -->
    <div id="content">

        @include('admin.layouts.topbar')
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">


            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{ route('admin.posts.store') }}" enctype="multipart/form-data">
                        @method('post')
                        @csrf
                        <input type="hidden" name="author_id" value="{{ Auth::user()->id }}">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="subtitle">Description</label>
                            <input type="text" name="subtitle" class="form-control">
                            <div class=" form-group col-6">
                                <label for="image">Cover Image</label>
                                <input type="file" name="image" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="description">Content</label>
                                <textarea name="description" class="form-control" rows="4"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-block btn-danger btn-lg">Save Post</button>
                            </div>
                    </form>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
@endsection

resources/views/admin/post-edit.blade.php
@extends('admin.layouts.master')
@include('admin.layouts.sidebar')
@section('title', $post->title)
@section('title')
@section('content')
    <div id="content">
        @include('admin.layouts.topbar')
        <div class="container-fluid">

            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{ route('admin.posts.update', $post->id) }}"
                        enctype="multipart/form-data">
                        @method('put')
                        @csrf
                        <input type="hidden" name="author_id" value="{{ Auth::user()->id }}">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control" value="{{ $post->title }}">
                        </div>
                        <div class="form-group">
                            <label for="subtitle">Description</label>
                            <input type="text" name="subtitle" class="form-control" value="{{ $post->subtitle }}">
                        </div>
                        <div class="form-group col-6">
                            @if ($post->image)
                                <a href="{{ asset($post->image) }}" traget="_blank">
                                    <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-responsive"
                                        style="width: 200px;">
                                </a>
                            @endif
                            <br> <br>
                            <input type="file" name="image" class="form-control" value="{{ asset($post->image) }}">
                        </div>
                        <div class="form-group col-6">
                            <label for="status">Status</label>
                            <select name="status" class="form-control">
                                <option @if ($post->status === 'publish') selected @endif value="publish">Publish</option>
                                <option @if ($post->status === 'draft') selected @endif value="draft">Draft</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">Content</label>
                            <textarea name="description" class="form-control"
                                rows="4">{{ $post->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-block btn-danger btn-lg">Update</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
        
    </div>
@endsection

resources/views/admin/posts.blade.php
@extends('admin.layouts.master')
@include('admin.layouts.sidebar')
@section('title', 'Blog Post')
@section('content')
    @include('admin.layouts.topbar')
    <div class="container-fluid">

        @if (Session::has('success'))
        @endif

        <div class="mb-4 shadow card">
            <div class="py-3 card-header">
                <h6 class="float-right m-0 font-weight-bold text-primary">
                    <a href="{{ route('admin.posts.create') }}" class="btn btn-danger rounded-pill">
                        <i class="fa fa-plus"></i>
                       New Post
                    </a>
                </h6>
                
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th style="width: 150px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $post)
                                <tr>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ $post->subtitle }}</td>
                                 
                                    <td>
                                        @if ($post->status == 'publish')
                                            <span class="badge badge-danger">Publish</span>
                                        @elseif($post->status == 'draft')
                                            <span class="badge badge-dark">Draft</span>
                                        @endif
                                    </td>
                                    <td @if ($post->author != Auth::user()) style="display: none;" @endif>
                                        <a href="{{ route('admin.posts.edit', $post->id) }}" class="btn btn-danger"><i class="fas fa-pencil-alt"></i></a>
                                        <a href="{{ route('admin.posts.destroy', $post->id) }}" class="btn btn-dark"><i
                                                class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/register.blade.php
@include('admin.layouts.header')
@section('title', 'Register')

    <body class="bg-gradient-primary">
        <div class="container">

            <div class="my-5 border-0 shadow-lg card o-hidden">
                <div class="p-0 card-body">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                        <div class="col-lg-7">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="mb-4 text-gray-900 h4">Register</h1>
                                </div>
                                <form method="post" action="{{ route('register.post') }}" class="user">
                                    @csrf
                                    <div class="form-group row">
                                        <div class="mb-3 col-sm-6 mb-sm-0">
                                            <input type="text" name="firstname" class="form-control form-control-user"
                                                id="exampleFirstName" placeholder="name">
                                        </div>
                                        <div class="col-sm-6">
                                            <input type="text" name="lastname" class="form-control form-control-user"
                                                id="exampleLastName" placeholder="Last Name">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" class="form-control form-control-user"
                                            id="exampleInputEmail" placeholder="Email Addres">
                                    </div>
                                    <div class="form-group row">
                                        <div class="mb-3 col-sm-6 mb-sm-0">
                                            <input type="password" name="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        {{-- <div class="col-sm-6">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleRepeatPassword" placeholder="Confirm">
                                        </div> --}}
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Register
                                    </button>
                                    <hr>
                                    <a href="index.html" class="btn btn-google btn-user btn-block">
                                        <i class="fab fa-google fa-fw"></i> Google
                                    </a>
                                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                        <i class="fab fa-facebook-f fa-fw"></i> Facebook
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="forgot-password.html"></a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{{ route('login') }}">Login</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </body>
    @include('admin.layouts.script')

resources/views/admin/users.blade.php
@extends('admin.layouts.master')
@include('admin.layouts.sidebar')
@section('title', 'Documentation')
@section('content')
    @include('admin.layouts.topbar')
    <div class="container-fluid">
        @if (Session::has('success'))
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i> {{ Session::get('success') }}
            </div>
        @endif
@include('errors.300')
        </div>

@endsection