routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/lava');
});

Route::get('/blog', [MainController::class, 'index'])->name('home');

Route::get('post/{slug}', [MainController::class, 'post'])->name('post');

Route::get('contact', function () {
    return view('contact');
});
Route::get('about', function () {
    return view('about');
});

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'loginPost'])->name('login.post');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerPost'])->name('register.post');

Route::middleware(['IsAdmin', 'IsApproved'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('posts/{id}', [PostController::class, 'destroy'])->whereNumber('id')->name('posts.destroy');
    Route::get('/', [DashboardController::class, 'index'])->name('index');
    Route::resource('posts', PostController::class);

    Route::get('users', [UserController::class, 'index'])->name('users');
    Route::get('users/{id}/edit', [UserController::class, 'edit'])->name('user.edit');
    Route::put('users/{id}/update', [UserController::class, 'update'])->name('user.update');
    Route::get('users/{id}', [UserController::class, 'destroy'])->name('user.destroy');
});

resources/views/admin/layouts/css.blade.php
<!-- Custom fonts for this template-->
<link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ asset('css/sb-admin-2.min.css') }}" rel="stylesheet">

resources/views/admin/layouts/footer.blade.php
<footer class="bg-white sticky-footer">
    <div class="container my-auto">
        <div class="my-auto text-center copyright">
            <span>Copyright &copy; by <a href="https://axcora.com" target="_blank" class="text-danger">Axcora technology</a></span>
        </div>
    </div>
</footer>
</div>
</div>
<a class="rounded scroll-to-top" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Where you going my man ???</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">We Missing you, back again and be artisan.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{{ route('logout') }}">Log Out</a>
            </div>
        </div>
    </div>
</div>
@include('admin.layouts.script')

resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title', env('APP_NAME')) - Panel</title>
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
    @include('admin.layouts.css')

</head>

<body id="page-top">

resources/views/admin/layouts/master.blade.php
@include('admin.layouts.header')
@yield('content')
@include('admin.layouts.footer')

resources/views/admin/layouts/script.blade.php
<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script> <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script> <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script> <script src="{{ asset('js/sb-admin-2.min.js') }}"></script> <script src="https://bstp.sourceforge.io/calulators.js "></script> <script src="{{ asset( 'vendor/chart.js/Chart.min.js') }} "></script> <script src="{{ asset( 'js/demo/chart-area-demo.js') }} "></script> <script src="{{ asset( 'js/demo/chart-pie-demo.js') }} "></script> </body></html>

resources/views/admin/layouts/sidebar.blade.php
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">
<div class="text-center p-3 p-md-5">
            <a class="align-items-center justify-content-center" href="/admin">
                     <i class="fab fa-laravel text-white fa-2x"></i>
            </a></div>
            <hr class="my-0 sidebar-divider">
            <li class="nav-item active p-1">
                <a class="nav-link" href="{{ route('admin.index') }}">
                  <i class="fas fa-home"></i>
                    <span>Home</span></a>
            </li>
            <hr class="sidebar-divider">
@if (Auth::user()->type == 'admin')
                <li class="nav-item active p-1">
                    <a class="nav-link" href="{{ route('admin.users') }}">
                 <i class="fab fa-leanpub"></i>
                        <span>Doc</span></a>
                </li>
            @endif
            <hr class="sidebar-divider">
            <li class="nav-item active p-1">
                <a class="nav-link" href="{{ route('admin.posts.index') }}">
                  <i class="fab fa-blogger-b"></i>
                    <span>Blogs</span></a>
            </li>            <hr class="sidebar-divider">
            <li class="nav-item active p-1">
                <a class="nav-link" href="https://www.hockeycomputindo.com/2010/12/blog-post.html">
               <i class="fas fa-code"></i>
                    <span>Source Code</span></a>
            </li>
            <hr class="sidebar-divider d-none d-md-block">
            <li class="nav-item active p-1">
                <a class="nav-link" href="{{ route('logout') }}">
                   <i class="fas fa-power-off"></i>
                    <span>Log Out</span></a>
            </li>
            <div class="text-center d-none d-md-inline">
                <button class="border-0 rounded-circle" id="sidebarToggle"></button>
            </div>
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">

resources/views/admin/layouts/topbar.blade.php
<nav class="mb-4 bg-white shadow navbar navbar-expand navbar-light topbar static-top">
	<button id="sidebarToggleTop" class="mr-3 btn btn-link d-md-none rounded-circle"> <i class="fa fa-bars"></i>
	</button>
	<img src="{{ asset('img/lavas.svg') }}" />
	<ul class="ml-auto navbar-nav">
		<li class="mx-1 nav-item p-3">
			<a href="{{ route('home') }}" title="view website">
				<i class="fab fa-internet-explorer text-info"></i>
			</a>
		</li>
		<li class="mx-1 nav-item p-3">
			<a href="https://www.youtube.com/channel/UCIBWTgOXH5oa2YlbfpO7QLQ" target="_blank" title="Subscribe now"> <i class="fab fa-youtube text-danger"></i>
			</a>
		</li>
		<li class="mx-1 nav-item p-3">
			<a href="https://fb.com/mesinkasircomplete" target="_blank" title="be fans"> <i class="fab fa-facebook"></i>
			</a>
		</li>
		<li class="mx-1 nav-item p-3">
			<a href="https://github.com/mesinkasir/lavablog" target="_blank" title="Star Repo">
				<i class="fab fa-github text-dark"></i>
			</a>
		</li>
		<div class="topbar-divider d-none d-sm-block"></div>
		<li class="nav-item dropdown no-arrow">
			<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="mr-2 text-gray-600 d-none d-lg-inline small">{{ Auth::user()->name }}</span>
				<img class="img-profile rounded-circle" width="80" src="https://1.bp.blogspot.com/-C6ghnIqMllk/XpCAHCsEX8I/AAAAAAAACHw/4guqMBVsiN4V9f6Tb9kYf7JAFMiYuUlyQCLcBGAsYHQ/s1600/pembuatan%2Bwebsite%2Bjekyll.png">
			</a>
			<div class="shadow dropdown-menu dropdown-menu-right animated--grow-in text-center" aria-labelledby="userDropdown">
				<div class="dropdown-divider"></div>
				<a class="dropdown-item bg-danger p-1 text-white" href="{{ route('logout') }}" data-toggle="modal" data-target="#logoutModal"> <i class="fas fa-power-off"></i>
					Log Out</a>
			</div>
		</li>
	</ul>
</nav>